services:
  db:
    image: postgres:16
    container_name: apm-postgres
    restart: always
    environment:
      POSTGRES_USER: apm_user
      POSTGRES_PASSWORD: apm_password
      POSTGRES_DB: apm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: